### ISSUE TITLE
Do we want to incorporate an AMREx-based example (maybe TDD) for ATPESC?

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/hello-numerical-world#8]
Per discussion on the 2021-06-03 telecon, if we really want to have an AMREx-based hands-on example, ATPESC would be the best target.  The students will do the numerical libraries track before ours, so they'd be ready.

It is not clear how many other opportunities we'd have to use it, but if we design it (as we always do) so students can work on their own, it might be nice to just have it out there.

**Comment by markcmiller86** [comment]
If this is pursued, I would like to see if it can be done in such a way as to at least be able to reproduce 1D heat equation results from hello-numerical-world. If it can do more than that (it easily could and probably should), that would be great. But, having the ability to compare/contrast the *software engineering experience* in doing things from scratch (e.g. hello-numerical-world) or using a framework, would be great.

**Comment by frobnitzem** [comment]
FYI - I timed the compile on my linux laptop, and it's 43 seconds using make -j on a 6-core intel-i7 (skylake).

I like the old-school charm of the hand-coded, stand-alone source.  But having written (and thrown away) a lot of those in the past, for new projects I'd much rather use good, well-documented, tested pre-built input file parser and scalar field class objects rather than re-implementing them again.  This should make the example code smaller, but more importantly it should give some credit to ECP projects for developing re-usable components.  Amrex has good documentation and, as far as I can tell, good development practices - so we should acknowledge that.  I also view teaching students to lookup, test, and use APIs as a good thing in the modern context.  Building software from scratch is good for learning bottom-up, but we also need to teach the top-down method of assembling good components.

Note that amrex does have build-tests for linux, mac-os, and linux platforms:
https://github.com/AMReX-Codes/amrex-tutorials/tree/main/.github/workflows

**Comment by markcmiller86** [comment]
@frobnitzem I don't think the time to compile, alone, is the biggest concern. For anyone wanting to do hands on with AMReX, I think the question is what will `spack install amrex` take? That will almost certainly be much, much longer than 43 seconds. It needs to download all the dependencies, build of the them and then finally compile and build AMReX. Also, not everyone will have an i7 machine.

The reason for a hand-coded example like the hello-numerical-world stuf is not to be *vintage* or *old-school* or to be *charming*. The reason is to have something that is extremely simple so more likely to be understood quickly during time crunched agendas, generic so its likely to compiles/builds everywhere yet still does some useful science, can be used to demonstrate simple concepts like threads or MPI parallelism (it doesn't now but that is a plan in my mind's eye) as well as CI, coverage, etc.

**Side note**: I didn't even want it to be C++ but wound up doing that to count operations and memory usage. Up until recently PAPI (which would have introduced an undesireable dependency) didn't work on ANL machines like Cooley or Vesta. So, I wound up adding a `Double` class to hello-numerical-world so we could easily do some operation counts and measure memory usage like PAPI does.

Another reason for hand-coded examples is to help learners understand the difference between writing stuff from scratch, which frankly is what a lot of academicians do, and learning to integrate with a larger, more complex framework. Frameworks come with a steep learning curve which is often seen as prohibitive relative to writing some stuff from scratch just to get a publication out. There are tradeoffs to consider and a useful role we can perform is to help learners understand what those tradeoffs are.

I am not saying that doing something with AMReX (or MFEM for that matter) isn't a great idea. I think it is! 😀  But I don't think it should be done *instead* of hand-coded examples like hello-numerical-world. It should be *in addition to* them and to use to compare not only the software engineereing involved but even the results, the workflows one uses to compute results, etc.

Whenever I teach the hello-world-example, I always point  out some of the items elaborated on [here](https://xsdk-project.github.io/MathPackagesTraining2020/lessons/hand_coded_heat/#challenges-with-custom-coding).

**Comment by bernhold** [comment]
I would amplify what Mark says about simplicity.  And also minimizing dependencies. And tools. The setting is not that of a regular class, where students do these exercises as homework and have time to work out issues that might arise.  They're part of a very time-limited activity where we have no control over the computing environment of the students.  We don't have time to hand-hold a class full of people through downloading and building fairly sophisticated software on some random collection of laptops.

*Maybe* if we could offer a platform that we control, where we could prebuild AMReX and everything else.  But that is also quite challenging (I've done tutorials that way too) in different ways.

**Comment by markcmiller86** [comment]
> _Maybe_ if we could offer a platform that we control

I think that would be containers of some form.

**Comment by bernhold** [comment]
Probably.  But we also can't depend on random users being able to deal with containers on their own hardware.  Many employers lock down company system and limit software installation.   We have to worry about things like the new Apple Arm-based systems.  And I have no idea about containers on Windows.  So that's a can of worms too.  (Last time I tried something like this, it was VMs, but the same principle applies.)

**Comment by bernhold** [comment]
@frobnitzem has raised this several more times.  In the most recent discussion (2021-12-16), @bernhold and @adubey64 remained very concerned about the significant complexity this would add to maintaining and teaching the hands-on in comparison with what they perceive as little benefit to the core topics on which the tutorial focuses.

With further discussion, we concluded that what @frobnitzem is really looking for is a different kind of hands-on module that is focused more on adoption of libraries and their integration into applications.  @bernhold and @adubey64 feel that this is beyond the goals of the usual BSSw tutorial, though it might be interesting for ATPESC.  More generally, it seems to us like something that xSDK might be interested in.  We also considered E4S adoption more generally, which is something Addi Malviya is working on with ExaAM, and looking at how IDEAS can contribute to capturing and broadening.

So we introduced @frobnitzem to Ulrike Yang, who leads xSDK for ECP and copied Addi, suggesting they meet and discuss.

**Comment by bernhold** [comment]
Based on the above, I think we have a path forward for @frobnitzem's idea that's outside of the BSSw tutorial.  So I'm going to close this issue, with the understanding that if it circles back to us, we can re-open or create a new ticket, as appropriate.
